### PR TITLE
feat!: changing openapi generator

### PR DESCRIPTION
**Pull request by seriouslag**
Changed openapi code generator to [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts).

Note: @hey-api/openapi-ts is rapidly changing its API.
We should consider that before merging to main.

Supporting new properties:
- --base
- --serviceResponse
- --enums
- --operationId
- --lint
- --format
- --useDateType (see below)

BREAKING CHANGE: 
--indent, --postfixModels, --postfixServices and --useUnionTypes properties were removed in @hey-api/openapi-ts.
Removed them from this API.

BREAKING CHANGE: 
I converted this library to a Javascript module, setting the type module in the package.json and changing TSC to compile to NodeNext. This is not a breaking change for most consumers of this package, but it could be for older node versions.

This was needed to build with @hey-api/openapi-ts.

Closes: #42 

I tested the --useDateType property. It works as specified in the @hey-api/openapi-ts library.
However, it only changes the generated model to a JS Date object and doesn't convert the string to a Date object.
As the model doesn't match the data.
I have opened an [issue](https://github.com/hey-api/openapi-ts/issues/145) in that library.

Note: I added a new library to help traverse TS source files, [ts-morph](https://github.com/dsherret/ts-morph)

### CODE REVIEW

**Comment by AnderssonPeter** [comment]
Will this pr also enable the date type? If I remember correctly they somehow converted dates to the JavaScript type Date, I'm a bit unsure if that happened automatically or if you had to enable it.

**Comment by seriouslag** [comment]
> Will this pr also enable the date type? If I remember correctly they somehow converted dates to the JavaScript type Date, I'm a bit unsure if that happened automatically or if you had to enable it.

The property is enabled, but I haven't tested it. Would be great if you could pull this branch and test your use case.

**Comment by AnderssonPeter** [comment]
Once this is merged and a new release has been created, then i could test it.

**Comment by AnderssonPeter** [comment]
> > Will this pr also enable the date type? If I remember correctly they somehow converted dates to the JavaScript type Date, I'm a bit unsure if that happened automatically or if you had to enable it.
> 
> The property can be enabled, but I still need to test it. If you can, please pull this branch and test your use case.

I tried to run it but I'm getting compilation errors, I'm a bit unsure how to run it from source..
I modified `examples\react-app\package.json` -> `generate:api` to be `node ../../dist/cli.js --useDateType -i ./swagger.json -o output`.

But when i run `npm run preview` in the root, i just get the error 
```
import { generate } from "./generate.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by seriouslag** [comment]
> > > Will this pr also enable the date type? If I remember correctly they somehow converted dates to the JavaScript type Date, I'm a bit unsure if that happened automatically or if you had to enable it.
> > 
> > 
> > The property can be enabled, but I still need to test it. If you can, please pull this branch and test your use case.
> 
> I tried to run it but I'm getting compilation errors, I'm a bit unsure how to run it from source.. I modified `examples\react-app\package.json` -> `generate:api` to be `node ../../dist/cli.js --useDateType -i ./swagger.json -o output`.
> 
> But when i run `npm run preview` in the root, i just get the error
> 
> ```
> import { generate } from "./generate.js";
> ^^^^^^
> 
> SyntaxError: Cannot use import statement outside a module
> ```

Thank you for testing it out. What version of node are you using?

**Comment by seriouslag** [comment]
@AnderssonPeter I tested the useDateType property. It works as specified in the [@hey-api/openapi-ts](https://github.com/hey-api/openapi-ts) library. However, it only changes the generated model to a JS Date object and doesn't convert the string to date. As the model doesn't match the data, I see this as useless and incorrect. I have opened an [issue in that library](https://github.com/hey-api/openapi-ts/issues/145).

**Review by 7nohe — APPROVED** [review]
@seriouslag That's excellent work. Thank you very much.
I would appreciate it if you could also make changes to the part on line 9 of the README.

> - Supports the option to use pure TypeScript clients generated by [OpenAPI Typescript Codegen](https://github.com/ferdikoomen/openapi-typescript-codegen)

**Comment by seriouslag** [comment]
> @seriouslag That's excellent work. Thank you very much. I would appreciate it if you could also make changes to the part on line 9 of the README.
> 
> > * Supports the option to use pure TypeScript clients generated by [OpenAPI Typescript Codegen](https://github.com/ferdikoomen/openapi-typescript-codegen)

Updated readme. Do we want to merge with the underlying client being below version one?

**Comment by mrlubos** [comment]
Hey all, we plan to provide a similar functionality (albeit with a different API) in the future in https://github.com/hey-api/openapi-ts. If you'd like to work on that package, feel free to reach out to me!

**Comment by seriouslag** [comment]
> Hey all, we plan to provide a similar functionality (albeit with a different API) in the future in https://github.com/hey-api/openapi-ts. If you'd like to work on that package, feel free to reach out to me!

What functionality?

**Comment by mrlubos** [comment]
@seriouslag we want to have an ecosystem of packages extending the core client

TypeScript interfaces -> API client (angular/axios/fetch) -> abstractions on top of it (TanStack Query, Nuxt, Next, Vue, etc.)

**Comment by mrlubos** [comment]
Thoughts @seriouslag ?

**Comment by seriouslag** [comment]
> Thoughts @seriouslag ?

An active PR is not a good place to self-promote your thoughts about planned functionality.
I want to collaborate, and I am sure others would as well.
Feel free to start working on your implementation if you think you can do a better job than what this project has done, and then open an issue in this repo if you care to.

**Comment by seriouslag** [comment]
> > > > > Will this pr also enable the date type? If I remember correctly they somehow converted dates to the JavaScript type Date, I'm a bit unsure if that happened automatically or if you had to enable it.
> > > > 
> > > > 
> > > > The property can be enabled, but I still need to test it. If you can, please pull this branch and test your use case.
> > > 
> > > 
> > > I tried to run it but I'm getting compilation errors, I'm a bit unsure how to run it from source.. I modified `examples\react-app\package.json` -> `generate:api` to be `node ../../dist/cli.js --useDateType -i ./swagger.json -o output`.
> > > But when i run `npm run preview` in the root, i just get the error
> > > ```
> > > import { generate } from "./generate.js";
> > > ^^^^^^
> > > 
> > > SyntaxError: Cannot use import statement outside a module
> > > ```
> > 
> > 
> > Thank you for testing it out.
> > What version of node/npm are you using?
> > To run from source:
> > 
> > * pull branch
> > * pnpm install
> > * change the openapi spec file (as it seems you did) in the example/react-app package.json
> > * `npm run preview` in root folder of project
> > 
> > It appears your source built and is failing on the `generate:api` step of example/react-apps package.json.
> 
> I'm fairly certain I did the steps you listed, I ran it on node 18 I think, but not 100 sure as I'm not at my PC.

I was able to duplicate the issue; I now converted all files to mjs, which I believe will fix this issue.
I would appreciate it if you could pull the latest and try again.

**Comment by seriouslag** [comment]
Updated PR to support the --useOptions of @hey-api/openapi-ts.
Also dropped all deprecated options.

**Comment by nopitown** [comment]
👏🏼 👏🏼 👏🏼 👏🏼  Looking forward this new generator.

**Comment by 7nohe** [comment]
It's working nicely on my PC, so let's go ahead and merge this and release it!

**Pull request merged**
