### PR TITLE
Bug: Fixed missing headers

### PR DESCRIPTION
**Pull request by Corepex**
Followup to: #46 

## Problem

It seems that the headers dont get passed to the request.

## Fix

I created a fix for that but it should be considered as "quick and dirty". 
**IMHO** there is a bigger problem with this part of the code generation. Also the names of the props are weird.

### CODE REVIEW

**Review by seriouslag — COMMENTED** [review]
How is this a bug? Does this solve an issue with the tests or fix the example?

Or should this change be added to the base request file?

**Comment by Corepex** [comment]
It is a bug because "special headers" like `Content-Type: application/merge-patch+json` don't get passed from the generated service to the request. 

In my case (for example) the `PATCH` method looks like that:
image

**Comment by seriouslag** [comment]
I see your case. This library is built on top of [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen). The default request file comes from that library. I am all for documenting your use case and fix in this package but a issue/PR in that library may be better for the ecosystem.

**Comment by 7nohe** [comment]
As @seriouslag said, the request file is not the responsibility of this library.
However, I think it makes a good example of how to customize headers, so I will accept this PR.

**Review by 7nohe — APPROVED** [review]

**Pull request merged**
