### PR TITLE
chore: Add biome

### PR DESCRIPTION
**Pull request by 7nohe**
- Use Biome to lint and format code
- Run Biome on CI (only on ubuntu-latest)
- Run Biome at pre-commit
- Upgrade pnpm to v9

https://biomejs.dev/

### CODE REVIEW

**Comment by seriouslag** [comment]
Biome looks cool, but with Eslint and Prettier, both being supported and used by @hey-api/open API-ts.

I would suggest we use those as I do not believe Biome to be such a benefit to lose out on compatibility checks. Maybe we can use biome for the root of the project and prettier/eslint for a specific test project but also why bother to do so.

**Comment by 7nohe** [comment]
@seriouslag 
Although this project depends on @hey-api/openapi-ts, I feel that linters and formatters are not very relevant. Moreover, managing plugins and rule settings with two separate packages, Prettier and ESLint, can be complex, so I would like to choose an option that is as simple and modern as possible.

**Comment by seriouslag** [comment]
> @seriouslag Although this project depends on @hey-api/openapi-ts, I feel that linters and formatters are not very relevant. Moreover, managing plugins and rule settings with two separate packages, Prettier and ESLint, can be complex, so I would like to choose an option that is as simple and modern as possible.

I understand what you are saying and disagree as I do not feel this is the same as you are saying.
We allow users to pass in options invoking the prettier/eslint config to run in the underlying tool. 
Being a wrapper and extension of the said package, we I feel we should use the same tooling.

We do not have to follow their same linting rules or anything just do not understand why we would deviate, it seems arbitrary to want to use a non-industry standard linter/formatter.

**Comment by 7nohe** [comment]
Indeed, you are right. I hadn't noticed that there is a new format option. I will close this PR. 
I've been seeing a trend of switching to Biome around me, so I thought it would be good to adopt it. It might be a good idea to suggest Biome for the @hey-api/openapi-ts project as well

**Pull request closed without merging**
