### PR TITLE
feat/new openapi client support 2

### PR DESCRIPTION
**Pull request by seriouslag**
- **feat: add support for new version of @heyapi and use fetch client instead of axios**
- **chore: remove comment**
- **chore: remove comment**
- **fix: make sure to remove not relevant props from params**
- **fix: get data from the client**
- **fix: get data from the client**
- **chore: release v1.4.2-beta.1**
- **fix: add formatters and linters on the queries output as well**
- **chore: release v1.4.2-beta.2**
- **chore: release v1.4.2-beta.3**
- **chore: release v1.4.2-beta.4**
- **chore: release v1.4.2-beta.5**
- **chore: release v2.0.0**
- **adding client support**

### CODE REVIEW

**Comment by seriouslag** [comment]
npm publish

**Comment by seriouslag** [comment]
npm publish

**Comment by seriouslag** [comment]
npm publish

**Comment by omridevk** [comment]
@seriouslag 
Do you recall how my commits got here? I am blanking here :P

**Comment by 7nohe** [comment]
@seriouslag @omridevk 
Thank you for updating the client and making the necessary changes accordingly. I apologize for the delayed response.
Since it’s not good to leave this unattended for too long, I will resolve the conflicts on my end, release it, and see how it is going in the real world.

**Comment by 7nohe** [comment]
I'll merge this for now and manage it in the v2 branch. Since there are still tests to be added and some issues that need to be addressed, I plan to release it once everything is completed.

**Pull request merged**
