### PR TITLE
Adding initialPageParam and nested nextPageParam support

### LINKED ISSUE #141: Support customizing `initialPageParam`
**Is your feature request related to a problem? Please describe.**
The newly added Infinite Query support generates a hard-coded `initialPageParam: 1`. This prevents use with cursor-based or zero-indexed pagination APIs.

**Describe the solution you'd like**
Support customizing the `initialPageParam`, be it null, string, or number.

**Describe alternatives you've considered**
I'll have to manually define the infinite query in the meantime, utilizing the generated API client.

### PR DESCRIPTION
**Pull request by adamgoose**
This adds a new argument `--initialPageParam` to customize the `initialPageParam` option passed to useInfiniteQuery. Defaults to 1.

Fixes #141.

---

When nextPageParam is set to meta.nextPage, split on . and generate the appropriately nested typehint:

```ts
  getNextPageParam: response => (response as {
    meta: {
      nextPage: number;
    };
  }).meta.nextPage
```

Fixes https://github.com/7nohe/openapi-react-query-codegen/issues/142.

### CODE REVIEW

**Review by seriouslag — APPROVED** [review]
Great change!

If you don't mind documenting the change in the readme that would be awesome. Thanks.

**Comment by adamgoose** [comment]
I've combined my two PRs into this one to prevent having to rebase and re-generate the snapshots between merges. I've also added docs as requested. 👍

**Review by 7nohe — APPROVED** [review]
Thank you for the awesome PR! It looks great!

**Comment by AnderssonPeter** [comment]
@adamgoose @7nohe this caused a breaking change, if you dont provide the `initialPageParam` parameter it now defaults to "initialPageParam", before it defaulted to "1"..
It would be nice if it still had 1 as default value.

**Pull request merged**
