### PR TITLE
feat: Update `@hey-api/openapi-ts` version and re-enable namespacing enums

### PR DESCRIPTION
**Pull request by collink**
I noticed that after updating to 1.4.1, that enums were being spit out next to the types instead of namespaced like previously.  After some digging, I found that this was a [`@hey-api/openapi-ts` issue](https://github.com/hey-api/openapi-ts/issues/557) which was [resolved this week with a PR](https://github.com/hey-api/openapi-ts/pull/835) and the [release of `v0.52.0`](https://github.com/hey-api/openapi-ts/releases/tag/%40hey-api%2Fopenapi-ts%400.52.0).

This PR does the following:
- bumps `@hey-api/openapi-ts` from `v0.45.1` => `v0.52.0`
  - this is to regain enum namespacing
- bumps `ts-morph` from `v22.0.0` => `v23.0.0`
  - this was to quiet some TS errors I was seeing
- bumps `typescript` from `v5.3.3` => `v5.5.4`
  - this was to quiet some TS errors I was seeing
- updates relevant tests
- updates relevant test snapshots

Looks like a huge diff, but it's almost entirely `pnpm-lock.json`, which we can just leave if you like, or you could re-run so that maybe the diff is smaller?

Why is this change important?  The issue is that if you have enums defined in your OAPI YAML, `@hey-api/openapi-ts` (prior to v0.52.0) is depositing the TS enums directly next to the types, so you end up with enums that look like this:

```typescript
export type Job = {
  // ...
  status: 'PENDING' | 'DONE',
  // ...
}

export enum status6 {
  PENDING: 'PENDING',
  DONE: 'DONE',
}
```

Before this change (and with this PR), that would look more like this:

```typescript
export type Job = {
  // ...
  status: 'PENDING' | 'DONE',
  // ...
}

export namespace Job {
  export enum status {
    PENDING: 'PENDING',
    DONE: 'DONE',
  }
}
```

It's SO much less ambiguous to be able to use `Job.status.DONE` in my code than `status6.DONE`. 😅

### CODE REVIEW

**Comment by collink** [comment]
@7nohe @seriouslag I saw that there's a couple-week-old PR open for bumping the `@hey-api/openapi-ts` version, but this one bumps it to the current version.  I was able to build and generate correctly without any major changes (just some type-related tweaks)

**Comment by 7nohe** [comment]
@collink Sorry for the late reply. I would appreciate it if you could resolve the conflicts.

**Comment by collink** [comment]
> @collink Sorry for the late reply. I would appreciate it if you could resolve the conflicts.

Done! 😄

**Comment by collink** [comment]
> @collink Sorry for the late reply. I would appreciate it if you could resolve the conflicts.

@7nohe no problem!  All done 😄

**Review by 7nohe — APPROVED** [review]

**Pull request merged**
